### ISSUE TITLE
World image sizes that don't perfectly match a View Area ratio will throw exception at borders.

### ISSUE THREAD

**Issue by djkool** [sam0s/sam0sRpgGame#1]
When generating a new area, we blindly try to access pixels in the World image, even though they may not exist. Resulting in the following backtrace:
```
Traceback (most recent call last):
  File "/src/sam0sRpgGame/game.py", line 193, in <module>
    game.update()
  File "/src/sam0sRpgGame/game.py", line 97, in update
    GameClass.update(self)
  File "/src/sam0sRpgGame/gamelib/game.py", line 23, in update
    self.curr_state.update()
  File "/src/sam0sRpgGame/game.py", line 169, in update
    w.move((p.x, p.y))
  File "/src/sam0sRpgGame/level.py", line 106, in move
    int(pos[1]/self.areaSize[1]) * self.areaSize[1]))
  File "/src/sam0sRpgGame/level.py", line 125, in _generateArea
    px = self._worldImg.get_at((world_pos[0] + i, world_pos[1] + j))
IndexError: pixel index out of range
```
This happens when trying to generate an Area at the right or bottom edge of the world. Our bounds checking only ensures the player cannot leave the world map, but it doesn't check for trying to generate the area outside of the world map when it doesn't fit perfectly into our View. This doesn't happen on the left or top bounds because the Areas start and are aligned perfectly to the origin (0,0).

**Comment by djkool** [comment]
Fixed by 69dc44fe0acdffe59acec8380a8c8c73e4908d7b.
